### ISSUE TITLE
Framework Agnostic?

### ISSUE THREAD

**Issue by triemstr** [madrobby/creditcard_js#2]
Hi I was wondering if there's any thought into merging in any of the framework agnostic versions?  There are two available:

https://github.com/remotezygote/creditcard_js

https://github.com/picomoney/creditcard_js

I can ask either one of them to do a pull request but I thought I'd get your thoughts first.

Thanks,
Kevin

**Comment by madrobby** [comment]
No, this version requires Prototype.js. Use one of the other versions if you want to run "bare metal".
